### ISSUE TITLE
Buttons on the Pocket will sometimes become unresponsive after booting a game

### ISSUE THREAD

**Issue by OngoGablogian** [frederic-mahe/Analogue-Pocket#11]
I've noticed that every now and again after booting a game (OEM Cart, Flashcart, or .pocket GB Studio game) the consoles buttons will become unresponsive until I power cycle the Pocket.  When this happens the home menu works as do all the buttons while in the Analogue OS, but nothing registers in game.

**Comment by zypherion** [comment]
I've seen this as well, on a legit Pokemon Pinball cart and on my Everdrive GB (Pre-x series).

**Comment by 16bitstreamer** [comment]
I have experienced this issue as well. Requires a hard power cycle. When returning to the Analogue Pocket menu the directional pad works but none of the other buttons work.

**Comment by TheMostSecret** [comment]
To add to this, I've also had it happen when waking the Pocket from sleep mode.
Also also, this can happen while docked too. Same deal, the controller will work in the Pocket menu but not in game. Undocking the Pocket doesn't help only restarting the Pocket fixes it.

**Comment by italiangrandma** [comment]
Can confirm I've experienced this issue a few times as well.

**Comment by OngoGablogian** [comment]
This issue was fixed as of Pocket firmware v1.0A.

**Comment by coolbho3k** [comment]
Awesome. Let's mark issue as resolved.
