### ISSUE TITLE
Add ability to force GBC mode on grey cartridge GB games

### ISSUE THREAD

**Issue by coolbho3k** [frederic-mahe/Analogue-Pocket#36]
There is currently no way to play an original Game Boy (grey) cartridge as if it were running on a GBC, so you miss out on the original LCD modes for GBC on these cartridges.

The only way to do this on the Pocket today is to use a flashcart to first boot the Pocket into GBC mode and then launch the grey cartridge game in GBC mode, but this is not possible on a real cartridge. It also works for GB games for which GBC detection is broken like Kirby's Dream Land. 

This is missing functionality from the Pocket that is present in the GBC. It would be important to have this alongside support for custom palettes that is planned. Adding a "Force GBC" toggle as well as palette options to the GBC core for GB games would fix this.

**Comment by toto99303** [comment]
+1 on this.

**Comment by coolbho3k** [comment]
A _possible_ alternative would be to allow the selection of the GBC LCD filter in GB mode, in addition to supporting custom palettes for GB games. Not sure if this gets us where we want 100% though.

**Comment by TheMostSecret** [comment]
I agree. I love all the screen modes but an option to have color palettes with LCD filter would be much appreciated.

**Comment by mddifilippo89** [comment]
I actually ran into a temporary issue where grey carts were booting in GBC mode. Force gb mode shouldn't impact grey carts but there does need to be an option to Force GBC mode to prevent confusion and other issues such as the one I ran into.

**Comment by coolbho3k** [comment]
Fixed with 1.0B
