### ISSUE TITLE
The Rugrats Movie (GBC) - Flashing HUD and background elements

### ISSUE THREAD

**Issue by italiangrandma** [frederic-mahe/Analogue-Pocket#38]
See title.

Tested via Everdrive GB. Tested on a real GBA and the issue does not occur.

**Comment by bvuillemin** [comment]
Hi! This problem occurs on a real cartridge as well. @italiangrandma and I discussed on Reddit about it. https://www.reddit.com/r/AnaloguePocket/comments/ryijcd/problem_with_rugrats_the_movie_on_gameboy_color

**Comment by JoseJX** [comment]
This appears to be an issue with Rugrats - Time Travelers as well: https://www.reddit.com/r/AnaloguePocket/comments/sf12es/graphical_glitches_in_rugrats_time_travelers/

**Comment by ace-dent** [comment]
I can confirm @JoseJX issue with "Rugrats - Time Travellers". 
Real Cart (DMG-AVMP-EUR). 
Pocket 1.0B. GBC Mode (no issue in DMG mode). 
Flashing HUD (window) element and background graphics. Becomes more broken on 2nd level 'Gold Rush'.

**Comment by italiangrandma** [comment]
Fixed as of Pocket firmware v1.1-beta (7/29/22)! Rugrats - Time Travelers is fixed as well.
