### ISSUE TITLE
Mickey's Speedway USA - Track Flicker

### ISSUE THREAD

**Issue by JoseJX** [frederic-mahe/Analogue-Pocket#49]
In the first race, the ground flickers with a green color instead of staying a light gray.

Tested on an EZ-Flash Jr. flash cart on the Pocket. It does not happen with the same ROM in an emulator (sameboy).

**Comment by francoiswnel** [comment]
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta
