### ISSUE TITLE
Gb modes

### ISSUE THREAD

**Issue by mddifilippo89** [frederic-mahe/Analogue-Pocket#55]
What's your thoughts on having all the available modes for GB?

Force GB
Force SGB
Force GBC
Force GBA - Sounds weird, but I am sure someone wants to play gb carts as cropped widescreen as played on a real gba when using the triggers.

**Comment by 16bitstreamer** [comment]
That's not what Force GBA does. There are a few GBC games that take advantage of the GBA's power to do extra things, Shantae for example. This allows those games to use those advantages where available. 

The options all have significate use, and I appreciate them greatly.

**Comment by bender-the-greatest** [comment]
Should we be using this tracker to discuss feature wishlists? This isn't an official issue tracker maintained by Analogue.

**Comment by 16bitstreamer** [comment]
I feel that the primary purpose for this tracker is to track issues and bugs.

**Comment by mddifilippo89** [comment]
1.0_B solves this. case closed
