### ISSUE TITLE
Analogue Pocket Dock: GBA Pixel Flickering in Firmware 1.0b

### ISSUE THREAD

**Issue by horntm** [frederic-mahe/Analogue-Pocket#59]
When in docked mode, GBA titles started exhibiting flickering pixels since the 1.0b update. I tried it on Tales of Phantasia, Mario Kart: Super Circuit, and Metroid Zero Mission (all original and clean GBA carts) in all display modes and resolutions. When undocked, the GBA games display normally on the Pocket. 

Gameboy titles do not display this pixel flickering at all either docked or undocked and display normally.

Again, the GBA pixel flickering issue in docked mode only showed up after updating to firmware ver. 1.0b. I also captured video of this flickering but had to resort to screenshots here. I'll be sharing the video in my support ticket to Analogue.

![Screenshot_20220203-011302~2](https://user-images.githubusercontent.com/74330055/152298193-c4842c6b-5bdc-4e3b-8346-ad57efcc94a4.png)
![Screenshot_20220203-011248~2](https://user-images.githubusercontent.com/74330055/152298195-5d6ab70a-635c-4f49-886b-88ecf5d9ee9a.png)
![Screenshot_20220203-011100~2](https://user-images.githubusercontent.com/74330055/152298196-877ab6cd-4429-4fbb-b168-3068bd2f2440.png)

**Comment by 16bitstreamer** [comment]
Duplicate to issue #56

https://github.com/frederic-mahe/Analogue-Pocket/issues/56

**Comment by horntm** [comment]
My apologies. This appears to have already been reported: #56.
