### ISSUE TITLE
Kirby Tilt 'n' Tumble resumes to white screen if sleep/wake function is used

### ISSUE THREAD

**Issue by treepizzahello** [frederic-mahe/Analogue-Pocket#61]
Kirby Tilt 'n' Tumble cart does not seem to work with the Pocket's sleep/wake function and resumes to a white screen when woke.

**Comment by manksalot** [comment]
I am able to reproduce this bug using firmware 1.0b with an original US cartridge.

**Comment by llakssz** [comment]
I'm on 1.0b, just want to add that this does not happen to me for the Japanese cart - game sleeps and wakes up fine.

**Comment by francoiswnel** [comment]
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta

**Comment by treepizzahello** [comment]
Confirmed this is fixed as of 1.1 beta.
