### ISSUE TITLE
Visual glitch on GB Nigel Mansell's World Championship Racing

### ISSUE THREAD

**Issue by noj86** [frederic-mahe/Analogue-Pocket#62]
Pocket: 1.0A
Cartridge: Original

Permanent visual glitch (blinking artefact / tile issue) in any of the racing mode.

**Comment by francoiswnel** [comment]
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta
