### ISSUE TITLE
[GBC] Simpsons THOH Glitching

### ISSUE THREAD

**Issue by mddifilippo89** [frederic-mahe/Analogue-Pocket#65]
https://i.imgur.com/C6t1Yih.gifv

**Comment by manksalot** [comment]
Looks like a duplicate of #42

**Comment by francoiswnel** [comment]
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta

**Comment by frederic-mahe** [comment]
thanks @francoiswnel
