### ISSUE TITLE
GBC Bugs Bunny & Lola - Glitched Sound on Pause

### ISSUE THREAD

**Issue by ace-dent** [frederic-mahe/Analogue-Pocket#67]
Original Cartridge (DMG-ABLP-UKV) "Bugs Bunny & Lola Bunny - Operation Carrot Patch".
Analogue Firmware 1.0B. GBC Mode.
Pressing 'Start' to Pause in level game, doesn't mute sound. It holds the note, making an unpleasant glitched sound.

**Comment by ace-dent** [comment]
Also affects Infogrames / Warner Bros game:
"Sylvester and Tweety - Breakfast on The Run". Original Cart (DMG-AYRP-UKV). DMG and GBC mode.

**Comment by JoseJX** [comment]
Also a problem with Sutte Hakkun GBC, does not happen on real GBC hardware but does on Pocket when using a flash cart.

**Comment by francoiswnel** [comment]
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta

**Comment by francoiswnel** [comment]
> Also a problem with Sutte Hakkun GBC, does not happen on real GBC hardware but does on Pocket when using a flash cart.

@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta
