### ISSUE TITLE
Robopon - Sun Version locks up

### ISSUE THREAD

**Issue by JoseJX** [frederic-mahe/Analogue-Pocket#72]
Robopon - Sun Version (U) crashes after showing the Hudson Logo with both a patched .pocket file and when using a flash cart.

**Comment by JoseJX** [comment]
This is probably due to the HuC-3 mapper used for this cart. I'd expect that the other carts that use this mapper would also exhibit issues.

**Comment by manksalot** [comment]
I have an original US cartridge and it loads past the Hudson logo, I can create a new game and play. So far functioning normally.
_Edit:_ I tried the sleep/wake function and get the "not supported by this cartridge" message.

**Comment by JoseJX** [comment]
Okay, interesting! So maybe it's a mapper issue with flash carts too? It was tested with an Everdrive by a user on the classic gaming Discord. So, perhaps we'll need to work around it another way then.

Thanks for testing with the original cart!

**Comment by BestPig** [comment]
I checked with my EverDrive on a GBA and the game is recognized as a MBC5 and it fails to run.
Also fails on real GBA with the game flashed in a bootleg.

So it's not an Analogue issue, just flashcard are not HuC-X compatible nether the GB Studio mode.

**Comment by JoseJX** [comment]
Okay, so this isn't a Pocket bug, thanks!
