### ISSUE TITLE
Rayman 3 (GBA) official cartridge

### ISSUE THREAD

**Issue by TheAmnesiacKid** [frederic-mahe/Analogue-Pocket#76]
I found a significant bug while playing through an official copy of Rayman 3 (GBA) on the 'Swamp of Begoniax' level (which happens to use 3D perspective). Everytime you jump (which is necessary to complete the level) the camera zooms wildly (reminds me of Mode 7 scaling on the SNES). I watched a YouTube video to see how to beat the level after dying several times and realized it is a severe, near game-breaking bug that isn't supposed to occur.

**Comment by francoiswnel** [comment]
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta
