### ISSUE TITLE
Golden Sun Overworld Map Shake

### ISSUE THREAD

**Issue by ninbura** [frederic-mahe/Analogue-Pocket#79]
There appears to be a rendering bug in Golden Sun that causes the overworld map to constantly shake, as can be seen in this video:
https://www.youtube.com/watch?v=9hqDNGUprH0

I've verified that this happens on the EZ Flash Omega Definitive Edition, a bootleg copy of Golden Sun, and an authentic copy of Golden Sun. It sounds like this has been an issue on emulators in the past:
https://www.reddit.com/r/GoldenSun/comments/et4hsh/playing_the_first_game_on_an_emulator_and_noticed/

I don't have the knowledge to understand the nature of this problem in relation to the Analogue Pocket, but when played on a normal Gameboy the map does not shake. Here's a video showing how the overworld map should look:
https://www.youtube.com/watch?v=9IEUOiixyEA

**Comment by GreatHierophant** [comment]
Turn Frame Blending on in the GBA Video menu and the map shake goes away.  This is caused by Golden Sun's rapid drawing of interlaced images, which older and slower LCDs will blend.
