### ISSUE TITLE
Golden Sun: TLA - Intern memory issues

### ISSUE THREAD

**Issue by Linktrm** [frederic-mahe/Analogue-Pocket#82]
There's some bugs left with Golden Sun: The Lost Age on Analogue Pocket.
I don't know when exactly but sometimes when I go save the game it says that there's some intern memory problems and it coudn't save.
I think it's after interacting into the Djinni menu in specific order. I don't know.
I've been playing a new game and progressed into the Dehkan Plateau (accquiring also the mercury djinni in Kandorean Temple). I was saving before fighting the Mars djinni and the error happened.

I'm playing the original "Golden Sun: La Edad Perdida" spanish cartrige AGB-002 on Analogue Pocket with firmware 1.0b.
Also played several times 100% with this cartridge with the original Game Boy Advance, SP and also Game Boy Player and never got that error.

Thanks a lot in advance.

**Comment by francoiswnel** [comment]
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes, though the wording of the notes are a bit different so I'm not sure. https://www.analogue.co/support/pocket/firmware/1.1-beta
