### ISSUE TITLE
Lucky Luke - Desperado Train

### ISSUE THREAD

**Issue by JoseJX** [frederic-mahe/Analogue-Pocket#83]
Using my EZ-Flash Jr. flash cart, this will eventually crash in the first level with a repeating background.

![20220428_233331](https://user-images.githubusercontent.com/459777/165881705-c10770ad-174f-4416-937b-51b8e0456648.jpg)

**Comment by francoiswnel** [comment]
@frederic-mahe This is reportedly fixed in the 1.1 beta according to the release notes. https://www.analogue.co/support/pocket/firmware/1.1-beta
