### ISSUE TITLE
[GBC] (OpenFPGA) Donkey Kong 5: The Journey of Over Time and Space (Unl, Bootleg) won't boot

### ISSUE THREAD

**Issue by italiangrandma** [frederic-mahe/Analogue-Pocket#92]
Using the "fixed" version of the rom. Loading the rom results in "Error"

Same results with the ED-GB flashcart.

**Comment by TheMostSecret** [comment]
Unless this is an issue with the physical cartridge you might want to add this to the openFPGA-GB-GBC git instead.
I've already got an issue open there about unlicensed mappers if you want to add this game to the list.
https://github.com/spiritualized1997/openFPGA-GB-GBC/issues/10
